; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit SSD1306@^2.5.17
	mathertel/OneButton@^2.6.2
    bblanchon/ArduinoJson @ ^7
board_build.filesystem = littlefs
monitor_speed = 115200
build_flags = -Iinclude

[env:native]
platform = native

build_flags =
    -std=gnu++17
    -D NATIVE_SIM
    -D ARDUINO=100
    -I$PROJECT_DIR/.native_stubs
    -I$PROJECT_DIR/include
    -lsfml-graphics
    -lsfml-window
    -lsfml-system

build_src_filter =
    +<*>
    +<../.native_stubs/*.cpp>

lib_deps =
    adafruit/Adafruit GFX Library

lib_ignore =
    Adafruit ST7735 and ST7789 Library
    Adafruit SSD1306
    OneButton
    Preferences
    EEPROM
    NetServer
    Adafruit BusIO
    DHT sensor library